# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mgc < Formula
  desc ""
  homepage "https://magalu.cloud"
  version "0.18.4-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MagaluCloud/mgccli/releases/download/v0.18.4-rc1/mgc_0.18.4-rc1_darwin_amd64.tar.gz"
      sha256 "d306e22d7d219de91001d8ac2a4854db306a5ef0381daf8bc5645b99a4bdc73a"

      def install
        bin.install "mgc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MagaluCloud/mgccli/releases/download/v0.18.4-rc1/mgc_0.18.4-rc1_darwin_arm64.tar.gz"
      sha256 "97f0725b4e6b728ba7bc1a898946ab664e139569742c645e26f6555ad6015b1d"

      def install
        bin.install "mgc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/MagaluCloud/mgccli/releases/download/v0.18.4-rc1/mgc_0.18.4-rc1_linux_amd64.tar.gz"
      sha256 "dd628f010de92c930a5a45711db082710ea875e73acfebce8863daedc0d2a9d6"

      def install
        bin.install "mgc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MagaluCloud/mgccli/releases/download/v0.18.4-rc1/mgc_0.18.4-rc1_linux_arm64.tar.gz"
      sha256 "41f242b9c3b3241757e150d63241aa61fb57b4d5554bcea52d3b8a27369dd4bd"

      def install
        bin.install "mgc"
      end
    end
  end
end
