# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mgccli < Formula
  desc ""
  homepage "https://magalu.cloud"
  version "0.29.0"

  on_macos do
    on_intel do
      url "https://github.com/MagaluCloud/mgccli/releases/download/v0.29.0/mgccli_0.29.0_darwin_amd64.tar.gz"
      sha256 "621e89fcb0fced038ae044b867e5bf05640b0b2ea0fd28f5cbcf21427cad6a28"

      def install
        bin.install "mgc"
      end
    end
    on_arm do
      url "https://github.com/MagaluCloud/mgccli/releases/download/v0.29.0/mgccli_0.29.0_darwin_arm64.tar.gz"
      sha256 "c6c8a2155d32ed269545813751fae8ce05f06bdbb28c7d76cef06c6fec3f70e9"

      def install
        bin.install "mgc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MagaluCloud/mgccli/releases/download/v0.29.0/mgccli_0.29.0_linux_amd64.tar.gz"
        sha256 "19e493e5c9ce1748f41eefc16349a0e9492f4ccbe4c29f743e6d89cc26c59142"

        def install
          bin.install "mgc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MagaluCloud/mgccli/releases/download/v0.29.0/mgccli_0.29.0_linux_arm64.tar.gz"
        sha256 "59244dec99023203ae4dd896996b88413416682fdf91561afa41f2b3ba055167"

        def install
          bin.install "mgc"
        end
      end
    end
  end
end
