# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mgccli < Formula
  desc ""
  homepage "https://magalu.cloud"
  version "0.24.2"

  on_macos do
    on_intel do
      url "https://github.com/MagaluCloud/mgccli/releases/download/v0.24.2/mgccli_0.24.2_darwin_amd64.tar.gz"
      sha256 "e1d14b3f133f449d715849ab76ab92fe76023541c53abd2e2258ed7647c51d3e"

      def install
        bin.install "mgc"
      end
    end
    on_arm do
      url "https://github.com/MagaluCloud/mgccli/releases/download/v0.24.2/mgccli_0.24.2_darwin_arm64.tar.gz"
      sha256 "697ff8731c5fc162658268e27fe3b41dd57a586408c5608d1d4576d2cf500308"

      def install
        bin.install "mgc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MagaluCloud/mgccli/releases/download/v0.24.2/mgccli_0.24.2_linux_amd64.tar.gz"
        sha256 "284c55a8012ca9bee4b8d4b16a0fd6af41b775f94a9b42241bc09923ffdd2644"

        def install
          bin.install "mgc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MagaluCloud/mgccli/releases/download/v0.24.2/mgccli_0.24.2_linux_arm64.tar.gz"
        sha256 "7cd84963a92b53e06c3ba126459d14138389588f889e008c35a66b786043eab7"

        def install
          bin.install "mgc"
        end
      end
    end
  end
end
